name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Inter font
        run: |
          sudo apt-get install -y fonts-inter
          fc-cache -f -v
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - name: Build
        run: 'yarn build --base="/frontex-assets/"'
      - name: Generate images
        run: |
          yarn playwright install chromium --with-deps
          yarn generateImages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: |
          curl -X POST "${{ secrets.PUBLISH_URL }}"
